/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:827fe51c-a064-425f-aee4-8ae6724ce6e9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JVismFOJq",
    "aws_user_pools_web_client_id": "1d6gfs78u7vnslmd92pfbhggf6",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "api7ed8d08c",
            "endpoint": "https://15h11oxwd2.execute-api.us-east-1.amazonaws.com/backend",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://xzw6twh5grgr7gqqrdsxv3bjwe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ez53neudurfvlhvwsmci4wriuu"
};


export default awsmobile;
